use std::env;
use std::fs;
use std::path::Path;
use std::time::SystemTime;

/// small wrapper for fetching environment variables
fn get_env(key: &str, default: &str) -> String {
    match env::var(key) {
        Ok(val) => val,
        Err(_) => default.to_string()
    }
}

fn main() {
    let git_version = get_env("GIT_VERSION", "head");
    let git_branch = get_env("GIT_BRANCH", "branch");
    let build_time = get_env("BUILD_TIME", "date");
            
    let dest_path = Path::new("src/cli/version.rs");
    fs::write(
        &dest_path,
        format!("// auto generated by build.rs
        pub const GIT_VERSION: &str = \"{git_version}\";
        pub const GIT_BRANCH: &str = \"{git_branch}\";
        pub const BUILD_TIME: &str = \"{build_time}\";
        ")
    ).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
}
